trigger:

  - main
 
jobs:

- job: RunPythonScripts

  steps:

  - task: UsePythonVersion@0

    inputs:

      versionSpec: '3.11'  # Use Python 3.11

      addToPath: true
 
  # Run initial_file.py with specified arguments

  - script: |

      python RELEASE_CONFIGURATIONS/initial_file.py $(Config_names)

    displayName: 'Run initial_file.py'
